// County -> municipality lists and the priority options the AI City Brief accepts.
// The brief route only answers for these values, so it cannot be used as a general chatbot.

export const COUNTIES = {
  "cook": {
    "label": "Cook County",
    "cities": [
      "Alsip",
      "Arlington Heights",
      "Barrington",
      "Barrington Hills",
      "Bartlett",
      "Bedford Park",
      "Bellwood",
      "Bensenville",
      "Berkeley",
      "Berwyn",
      "Blue Island",
      "Bridgeview",
      "Broadview",
      "Brookfield",
      "Buffalo Grove",
      "Burbank",
      "Burnham",
      "Burr Ridge",
      "Calumet City",
      "Calumet Park",
      "Chicago",
      "Chicago Heights",
      "Chicago Ridge",
      "Cicero",
      "Country Club Hills",
      "Countryside",
      "Crestwood",
      "Deer Park",
      "Deerfield",
      "Des Plaines",
      "Dixmoor",
      "Dolton",
      "East Dundee",
      "East Hazel Crest",
      "Elgin",
      "Elk Grove Village",
      "Elmhurst",
      "Elmwood Park",
      "Evanston",
      "Evergreen Park",
      "Flossmoor",
      "Ford Heights",
      "Forest Park",
      "Forest View",
      "Frankfort",
      "Franklin Park",
      "Glencoe",
      "Glenview",
      "Glenwood",
      "Golf",
      "Hanover Park",
      "Harvey",
      "Harwood Heights",
      "Hazel Crest",
      "Hickory Hills",
      "Hillside",
      "Hinsdale",
      "Hodgkins",
      "Hoffman Estates",
      "Homer Glen",
      "Hometown",
      "Homewood",
      "Indian Head Park",
      "Inverness",
      "Justice",
      "Kenilworth",
      "La Grange",
      "La Grange Park",
      "Lansing",
      "Lemont",
      "Lincolnwood",
      "Lynwood",
      "Lyons",
      "Markham",
      "Matteson",
      "Maywood",
      "McCook",
      "Melrose Park",
      "Merrionette Park",
      "Midlothian",
      "Morton Grove",
      "Mount Prospect",
      "Niles",
      "Norridge",
      "North Riverside",
      "Northbrook",
      "Northfield",
      "Northlake",
      "Oak Brook",
      "Oak Forest",
      "Oak Lawn",
      "Oak Park",
      "Olympia Fields",
      "Orland Hills",
      "Orland Park",
      "Palatine",
      "Palos Heights",
      "Palos Hills",
      "Palos Park",
      "Park Forest",
      "Park Ridge",
      "Phoenix",
      "Posen",
      "Prospect Heights",
      "Richton Park",
      "River Forest",
      "River Grove",
      "Riverdale",
      "Riverside",
      "Robbins",
      "Rolling Meadows",
      "Roselle",
      "Rosemont",
      "Sauk Village",
      "Schaumburg",
      "Schiller Park",
      "Skokie",
      "South Barrington",
      "South Chicago Heights",
      "South Holland",
      "Steger",
      "Stickney",
      "Stone Park",
      "Streamwood",
      "Summit",
      "Thornton",
      "Tinley Park",
      "University Park",
      "Westchester",
      "Western Springs",
      "Wheeling",
      "Willow Springs",
      "Wilmette",
      "Winnetka",
      "Woodridge",
      "Worth"
    ]
  },
  "dupage": {
    "label": "DuPage County",
    "cities": [
      "Addison",
      "Aurora",
      "Bartlett",
      "Batavia",
      "Bensenville",
      "Bloomingdale",
      "Bolingbrook",
      "Burr Ridge",
      "Carol Stream",
      "Chicago",
      "Clarendon Hills",
      "Darien",
      "Downers Grove",
      "Elk Grove Village",
      "Elmhurst",
      "Glen Ellyn",
      "Glendale Heights",
      "Hanover Park",
      "Hinsdale",
      "Itasca",
      "Lemont",
      "Lisle",
      "Lombard",
      "Naperville",
      "Oak Brook",
      "Oakbrook Terrace",
      "Roselle",
      "Schaumburg",
      "St. Charles",
      "Villa Park",
      "Warrenville",
      "Wayne",
      "West Chicago",
      "Westmont",
      "Wheaton",
      "Willow Springs",
      "Willowbrook",
      "Winfield",
      "Wood Dale",
      "Woodridge"
    ]
  },
  "kane": {
    "label": "Kane County",
    "cities": [
      "Algonquin",
      "Aurora",
      "Barrington Hills",
      "Bartlett",
      "Batavia",
      "Big Rock",
      "Burlington",
      "Campton Hills",
      "Carpentersville",
      "East Dundee",
      "Elburn",
      "Elgin",
      "Geneva",
      "Gilberts",
      "Hampshire",
      "Hoffman Estates",
      "Huntley",
      "Kaneville",
      "Lily Lake",
      "Maple Park",
      "Montgomery",
      "North Aurora",
      "Pingree Grove",
      "Sleepy Hollow",
      "South Elgin",
      "St. Charles",
      "Sugar Grove",
      "Virgil",
      "Wayne",
      "West Dundee"
    ]
  },
  "kendall": {
    "label": "Kendall County",
    "cities": [
      "Aurora",
      "Joliet",
      "Lisbon",
      "Millbrook",
      "Millington",
      "Minooka",
      "Montgomery",
      "Newark",
      "Oswego",
      "Plainfield",
      "Plano",
      "Plattville",
      "Sandwich",
      "Yorkville"
    ]
  },
  "lake": {
    "label": "Lake County",
    "cities": [
      "Antioch",
      "Bannockburn",
      "Barrington",
      "Barrington Hills",
      "Beach Park",
      "Buffalo Grove",
      "Deer Park",
      "Deerfield",
      "Fox Lake",
      "Fox River Grove",
      "Grayslake",
      "Green Oaks",
      "Gurnee",
      "Hainesville",
      "Hawthorn Woods",
      "Highland Park",
      "Highwood",
      "Indian Creek",
      "Island Lake",
      "Kildeer",
      "Lake Barrington",
      "Lake Bluff",
      "Lake Forest",
      "Lake Villa",
      "Lake Zurich",
      "Lakemoor",
      "Libertyville",
      "Lincolnshire",
      "Lindenhurst",
      "Long Grove",
      "Mettawa",
      "Mundelein",
      "North Barrington",
      "North Chicago",
      "Old Mill Creek",
      "Park City",
      "Port Barrington",
      "Riverwoods",
      "Round Lake",
      "Round Lake Beach",
      "Round Lake Heights",
      "Round Lake Park",
      "Third Lake",
      "Tower Lakes",
      "Vernon Hills",
      "Volo",
      "Wadsworth",
      "Wauconda",
      "Waukegan",
      "Wheeling",
      "Winthrop Harbor",
      "Zion"
    ]
  },
  "mchenry": {
    "label": "McHenry County",
    "cities": [
      "Algonquin",
      "Barrington Hills",
      "Bull Valley",
      "Cary",
      "Crystal Lake",
      "Fox Lake",
      "Fox River Grove",
      "Greenwood",
      "Harvard",
      "Hebron",
      "Holiday Hills",
      "Huntley",
      "Island Lake",
      "Johnsburg",
      "Lake in the Hills",
      "Lakemoor",
      "Lakewood",
      "Marengo",
      "McCullom Lake",
      "McHenry",
      "Oakwood Hills",
      "Port Barrington",
      "Prairie Grove",
      "Richmond",
      "Ringwood",
      "Spring Grove",
      "Trout Valley",
      "Union",
      "Wonder Lake",
      "Woodstock"
    ]
  },
  "will": {
    "label": "Will County",
    "cities": [
      "Aurora",
      "Beecher",
      "Bolingbrook",
      "Braidwood",
      "Channahon",
      "Coal City",
      "Crest Hill",
      "Crete",
      "Diamond",
      "Elwood",
      "Frankfort",
      "Godley",
      "Homer Glen",
      "Joliet",
      "Lemont",
      "Lockport",
      "Manhattan",
      "Minooka",
      "Mokena",
      "Monee",
      "Naperville",
      "New Lenox",
      "Orland Park",
      "Oswego",
      "Park Forest",
      "Peotone",
      "Plainfield",
      "Rockdale",
      "Romeoville",
      "Shorewood",
      "Steger",
      "Symerton",
      "Tinley Park",
      "University Park",
      "Wilmington",
      "Woodridge"
    ]
  }
};

export const GOALS = {
  "downtown": "Revitalize the downtown or main street",
  "retail": "Attract retail and restaurants",
  "jobs": "Bring industrial and employment jobs",
  "housing": "Add housing, including affordable and mixed-use",
  "infra": "Fix roads, water, and other infrastructure",
  "vacant": "Redevelop vacant or contaminated sites"
};
